name: datadynamic-environment
channels:
  - conda-forge
dependencies:
  - python >= 3.7
  - jupyterlab
  - networkx
  - nltk
  - nodejs 
  - numpy
  - fancyimpute
  - numpy
  - pandas
  - cvxpy
  - xgboost
  - lightgbm
  - graphviz
  - imblearn
  - jupyterlab-git
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - pyecharts
    - pyecharts-snapshot
    - echarts-countries-pypkg
    - echarts-china-provinces-pypkg
    - echarts-china-cities-pypkg
    - pydot
    - pydotplus
    - pygraphviz
    - pycallgraph
    - transitions
    