name: datadynamic-environment
channels:
  - conda-forge
dependencies:
  - dask
  - distributed
  - python >= 3.7
  - jupyterlab
  - networkx
  - nltk
  - nodejs 
  - cvxpy
  - lightgbm
  - graphviz
  - jupyterlab-git
  - python-graphviz
  - scikit-learn
  - sympy
  - pip:
    - pycallgraph
    - transitions
    - nbgitpuller
    - xgboost
    - tushare
    - numpy
    - pandas
    - matplotlib
    - pyecharts
    - pyecharts-snapshot
    - echarts-countries-pypkg
    - echarts-china-provinces-pypkg
    - echarts-china-cities-pypkg
    - pydot
    - pydotplus
    - pygraphviz
    - pycallgraph
    - transitions
    - fancyimpute
    - imblearn
