name: jupyterlab_graphviz
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - distributed
  - graphviz
  - networkx
  - nltk
  - nodejs
  - pydot
  - pydotplus
  - pygraphviz
  - pylint
  - python >=3.6,<3.7
  - python-graphviz
  - scikit-learn
  - sympy
  - pip:
    - pycallgraph
    - transitions