name: datadynamic-environment
channels:
  - conda-forge
  - default
dependencies:
  - python >= 3.6
  - jupyterlab
  - jupyterhub
  - nodejs 
  - jupyterlab-git
  - bokeh
  - pip:
    - transitions
    - ipywidgets
    - nbgitpuller
    - nbgrader
    - xgboost
    - sklearn
    - tushare
    - numpy
    - pandas
    - scipy
    - matplotlib
    - perspective-python
    - mpl_finance
    - plotly
    - tqdm
    - statsmodels
    - boto