name: datadynamic-environment
channels:
  - conda-forge
dependencies:
  - python >= 3.6
  - jupyterlab
  - jupyterhub
  - nodejs 
  - jupyterlab-git
  - bokeh
  - pip:
    - transitions
    - ipywidgets
    - nbgitpuller
    - nbgrader
    - xgboost
    - tushare
    - numpy
    - pandas
    - scipy
    - matplotlib
    - perspective-python
    - mpl_finance
    - plotly
    - tqdm
    - statsmodels
    - boto
    - sklearn
    - echarts
    - pyecharts
    - pyecharts-snapshot
    - echarts-countries-pypkg
    - echarts-china-provinces-pypkg
    - echarts-china-cities-pypkg
