#!/bin/bash

# Install JupyterLab extension

# install graphviz extension


jupyter labextension install @jupyterlab/hub-extension
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git

jupyter labextension install jupyterlab_graphviz

jupyter nbextension install echarts
jupyter nbextension enable echarts/main